[package]
name = "matching_engine"
version = "0.1.0"
authors = ["Jacob Reinertson <j.reinertson@hotmail.com>"]
edition = "2018"

[dependencies]


[dependencies.tibrv]
version = "0.4.0"
features = ["tibrv_8_4"]